Ms/1095 history user not recorded in history objects
acdh-oeaw/apis-core-rdf pull request #1096
Opened 2024-08-23 09:52 UTC by sennierer

2024-10-07 07:22 UTC, b1rger requested changes
please rebase ;)

2024-10-07 07:22 UTC, b1rger commented on docs/source/features.rst
> +the request object to the current user. This attribute is then used by the
```suggestion
the request object to the current user. It then saves this information to the `history_user` attribute of the historical record. 
```

2024-10-07 07:22 UTC, b1rger commented on docs/source/features.rst
> +`VersionMixin` to set the `history_user` attribute of the historical record.
```suggestion
```

2024-10-07 07:22 UTC, b1rger commented on docs/source/features.rst
> +        'apis_core.history.middleware.HistoryMiddleware',
```suggestion
        'apis_core.history.middleware.HistoryRequestMiddleware',
```

2024-10-07 14:45 UTC, b1rger commented
(I'm not sure if this is also something we want in our default settings - probably depends if we also want the `apis_core.history` app in the `INSTALLED_APPS`)

2024-10-08 11:40 UTC, sennierer commented
given that this is recording user names I suggest to just add the comments in the documentation on how to use it

2024-12-10 15:57 UTC, sennierer commented
> (I'm not sure if this is also something we want in our default settings - probably depends if we also want the `apis_core.history` app in the `INSTALLED_APPS`)

lets discuss that in another issue

2024-12-10 16:04 UTC, sennierer commented
@b1rger rebased it on main and added your suggested changes. I suggest to merge this and discuss whether to add it to default settings or not in another issue

2024-12-11 07:06 UTC, b1rger approved these changes

2024-12-11 07:09 UTC, merged