feat(generic): add DateTimeIntervalCharField
acdh-oeaw/apis-core-rdf pull request #1119
Opened 2024-08-29 10:52 UTC by b1rger

2024-08-29 12:52 UTC, sennierer commented
Is there a specific reason to use `DateTimeField` instead of `DateField`?
I guess our main use case (99%) has only dates and no time.

2024-11-18 11:07 UTC, sennierer requested changes

2024-11-18 11:07 UTC, sennierer commented on apis_core/generic/fields.py
> +        regex_patterns: List[Tuple[str, str, str]] = [
as discusssed remove the list here and add a doctring explaining the sequence of patterns: sort, from, to

2024-11-20 10:32 UTC, b1rger commented
I've reworked the FuzzyDateRegexField as well as the GenericDateIntervalField, which is the base for the regex and the parser fields. I had to redo the `contribute_to_class` method in the `GenericDateIntervalField` because there were, again, problems with the database migration. I've now taken inspiration from a solution from django-money, but it would be great if especially adding/removing fields would be battle tested

2024-12-10 17:14 UTC, sennierer commented
Just got a `django.db.utils.OperationalError: duplicate column name: date_of_birth_fuzzy_date_from` when using the new field.
Thats what I did:
- delete the sqlite db 
- add a field called `date_of_birth_fuzzy` with the `GenericDateIntervalField` 
- run `python manage.py makemigrations` 
- run `python manage.py migrate`

Got the error. Checked the migrations and there is no duplicate field definitions in the migrations.

2024-12-11 08:25 UTC, sennierer approved these changes
Working as intended. tested with the sample project, both fields. Removed and added fields without any migration issues.

2024-12-11 10:13 UTC, sennierer commented
We decided to publish the field as its own module.

2024-12-17 09:30 UTC, closed without merging

2025-02-10 10:53 UTC, koeaw commented
> We decided to publish the field as its own module.

Link to repo for reference: https://github.com/acdh-oeaw/django-interval