feat(relations): list relations under tabs
acdh-oeaw/apis-core-rdf pull request #1276
Opened 2024-10-08 13:27 UTC by gythaogg

This pull request includes an update to the `list_relations_include.html` template to enhance the user interface by switching from a card layout to a tabbed navigation layout.

UI Improvements:

* [`apis_core/relations/templates/relations/list_relations_include.html`](diffhunk://#diff-d04981e387d63223046d9453920a5aa0805ed95e4532e75e8261c074bb132adfR5-R20): Replaced the card layout with a tabbed navigation layout to improve the user experience. The new layout uses Bootstrap's tab component to organize relation targets into tabs.

closes #489 

TO DISCUSS

- [x] Potentially useful to have an ALL tab to have a quick overview and set that as default. ~This is not implemented in this pull request.~
- [ ] TibSchol users would prefer the tab headings to also show the number of relations under each tab so they don't have to cycle through all the tabs to see which one has content. Don't know if it is worth it (it was only a nice-to-have wish). 
- [ ] When you are in a particular tab and then do an action that causes the page to reload (by clicking on Edit, for example) then the first tab will be active again. 

~When new relations are created, they should be added to the correct element so that they are not displayed under all tabs~

After new relations are created, they appear correctly in the active tab but need a refresh for them to appear in the ALL tab.

2024-10-09 11:12 UTC, b1rger reviewed
Nice! We should discuss in JFX if this should be the default. An "ALL" tab would definitly make sene.

Regarding the problem with all relations being listed after a change: do you already know what we need to change to fix that? Mabye we have to refactor the `list_relations.html` template a bit and pass the target as an argument...

2024-10-15 11:00 UTC, sennierer commented
look into keeping both options
also see if anchor elements plus scrolling and rolling headers makes sense
also sorting of tables needs to be sorted

2024-10-15 14:16 UTC, b1rger commented
> @b1rger I tried to override the person template to use the tabbed view of relations for sample_project - [3f75d7f](https://github.com/acdh-oeaw/apis-core-rdf/commit/3f75d7f269785fe6f43b5960678e74fb98e8c361)
> 
> It looks like it displays the relations in tabs and via the block.super call, it also displays the relations in the grouped list format and I can't quite figure out how to skip the overridden template in `relations/templates/apis_core/apis_entities/... `and only run the super code in `apis_core/apis/entities/`
> 
> View ![image](https://private-user-images.githubusercontent.com/7236469/376634320-74e4a618-fd55-4b26-85ec-5f4e182a9024.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkwMDE3MDQsIm5iZiI6MTcyOTAwMTQwNCwicGF0aCI6Ii83MjM2NDY5LzM3NjYzNDMyMC03NGU0YTYxOC1mZDU1LTRiMjYtODVlYy01ZjRlMTgyYTkwMjQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTAxNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEwMTVUMTQxMDA0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NWQ4MzVkZjA0YzgzNDI1MDc2YTdmYTc5YTE4NjY1ZjQwM2IwYmVjMTJhMzVmOGQ4MzYwZWY5N2RlZDA4ZmMzZiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.rUleW1wLbjPM8Zjq4II9WxPAAcZX341IWT7fuMwXKGs)
> 
> Edit ![image](https://private-user-images.githubusercontent.com/7236469/376634550-1345419b-7653-4cca-a480-65a3c90f827e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkwMDE3MDQsIm5iZiI6MTcyOTAwMTQwNCwicGF0aCI6Ii83MjM2NDY5LzM3NjYzNDU1MC0xMzQ1NDE5Yi03NjUzLTRjY2EtYTQ4MC02NWEzYzkwZjgyN2UucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTAxNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEwMTVUMTQxMDA0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NTkzNDMyYjY2NzFjNmRkOTdlMmFlMjI5M2E2NjM0NTA1YWFjNjEyYWQ5NTY5YmQzYjIwYTI2NTU2ZDBkMjUwNCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.cr-B4iMwcV4vB4w77xAmg5Tb4mhWvTko6PI9kOK5Cy4)
> 
> Am I doing something wrong here?

Sorry, I'm not quite sure what you want to achieve. Why don't you drop the `{{ block.super }}`?

2024-10-18 06:06 UTC, b1rger requested changes
* Please move the introduction of the `relations-include` block into a separate PR
* I'm not sure what the "To Be Done" in one of the commit messges means - does it mean that this PR is still a draft and those things will be implemented? Or should those todos be implemented after the PR is merged?

2024-10-18 06:06 UTC, b1rger commented on apis_core/relations/templates/relations/list_relations.html
What is this change for?

2024-10-22 07:50 UTC, b1rger commented
> Without this change if I override col-one in my ontology (to point to the tabs relation template,- in the inheritance chain the call to block.super includes the col-one from the templates in relations first - which includes default listing of relations.

I'm not sure if we talk about the same change. I'm talking about the addition of the `ALL` if no target exists.

2024-10-23 07:13 UTC, b1rger requested changes

2024-10-23 07:13 UTC, b1rger commented on apis_core/relations/templates/relations/list_relations_include_tabs.html
> +         hx-swap-oob="true">{% include "relations/list_relations.html" %}</div>
There is still a `hx-swap-oob` leftover

2024-10-23 10:30 UTC, b1rger approved these changes

2024-10-23 10:33 UTC, merged