feat(core): introduce a MaintenanceMiddleware
acdh-oeaw/apis-core-rdf pull request #1395
Opened 2024-11-15 08:45 UTC by b1rger

Add a MaintenanceMiddleware that allows to set APIS in maintenance mode.
Maintenance mode allows superusers to access the site, but all other
requests get a simple maintenance page as a response.
This can be enabled by adding
`apis_core.core.middleware.MaintenanceMiddleware` to
`settings.MIDDLEWARE`. To active the maintenance mode simply create a
`/tmp/apis_maintenance` file. To deactivate maintenance mode, remove
that file.

Closes: #1296

2024-11-18 10:27 UTC, sennierer requested changes
Working as expected. Please add a logging info that the site is running in maintenance mode and a comment in the docs that the path of the maintenance file can be changed.

2024-11-18 10:27 UTC, sennierer commented on apis_core/core/middleware.py
> +
```suggestion

logger = logging.getLogger(__name__)
```

2024-11-18 10:27 UTC, sennierer commented on apis_core/core/middleware.py
> +        if Path(maintenance_file).exists():
```suggestion
        if Path(maintenance_file).exists():
            logger.warning("Site is running in maintenance mode")
```

2024-11-18 10:27 UTC, sennierer commented on docs/source/configuration.rst
> +create a file ``/tmp/apis_maintenance``.
```suggestion
create a file ``/tmp/apis_maintenance``. The path of the maintenance file can be changed in
the settings: ``APIS_MAINTENANCE_FILE = "path of the file"``.
```

2024-11-19 10:53 UTC, b1rger commented
Implemented the suggestions and set the default of `APIS_MAINTENANCE_FILE` to `apis_maintenance`

2024-12-10 16:29 UTC, sennierer approved these changes
works in my installations. Thanks!

2024-12-17 09:34 UTC, merged