feat(apis_entities): copy fields when merging entities
acdh-oeaw/apis-core-rdf pull request #142
Opened 2023-04-19 09:55 UTC by b1rger

This commit introduces a `merge_fields` method in the TempEntityClass.
It copies information for the relevant fields in TempEntityClass and can
be extended by subclasses to implement custom logic for copying custom
subclass fields.

2023-04-19 10:05 UTC, b1rger commented
Please note that I made some decisions about how attributes are merged- i.e. the `name` field gets concatenated with a comma. There might by better approaches.

2023-05-03 11:21 UTC, koeaw commented
@b1rger I'm not entirely clear on the long(er)-term purpose of this seeing as we're about to drop `TempEntityClass`. Is this supposed to be moved elsewhere later on? Or can this help with _moving away_ from `TempEntityClass`?

I had a look at the linked issue but am none the wiser. It's possible I'm only missing a bit of context here.

2023-05-03 11:37 UTC, b1rger commented
> @b1rger I'm not entirely clear on the long(er)-term purpose of this seeing as we're about to drop `TempEntityClass`. Is this supposed to be moved elsewhere later on? Or can this help with _moving away_ from `TempEntityClass`?
> 
> I had a look at the linked issue but am none the wiser. It's possible I'm only missing a bit of context here.

At the moment when entities are merged information gets lost and there is no way for ontologies to define how the local fields of their entities should be handled when merging is done. I don't believe that `TempEntityClass` will be going away that soon, so I think it makes sense to fix this problem

2023-05-24 11:59 UTC, sennierer requested changes
I think the merging is currently not completely concise:
`self` is overruling `other` on some fields, others are completely equal.
I think the object that something is merged into (so `self`) should be overruling `other` and this should also be reflected in the string based fields.

Given that this should work on all classes, so include also fields that are not inheritated from `RootObject` we could refactor that to run through all fields and depending on the field type (so whether its sting, date etc. always use the same logic/function on it.

2023-05-24 11:59 UTC, sennierer commented on apis_core/apis_entities/models.py
> +            self.name = ", ".join([self.name, other.name])
I think it should be rather
```python
self.name = f"{self.name} ({other.name})"
```
for the dates `self` is overruling `other` when both objects have dates, that should be reflected in the string based fields as well

2023-05-24 11:59 UTC, sennierer commented on apis_core/apis_entities/models.py
> +        self.references = "\n".join(filter(None, [self.references, other.references]))
see comment above. should be clear which comments stem from an object that was merged in the actual one (put in brackets or explicitly mentioned ... eg `references from merged objects:`

2023-05-25 14:26 UTC, b1rger commented
> Given that this should work on all classes, so include also fields that are not inheritated from RootObject we could refactor that to run through all fields and depending on the field type (so whether its sting, date etc. always use the same logic/function on it.

Oke, I've implemented that - the `merge_fields` method now iterates through the model fields and checks wether there is a `merge_{fieldname}` method and if so uses that. If not, it checks for a `merge_{fieldtype}` method and uses that. If no method exists and the field in `self` is empty, it copies the value of `other`.

I've implemented `merge_` methods for charfield, textfield and booleanfield. Given that `start_date_written` and `end_date_written` are parsed and the parsing would fail with the default merge method for charfields, I added extra methods for those two, demonstrating how the merge methods get chosen.

In the long run, some of the merge functionality should probably move to the RootObject or the AbstractEntity...

2023-05-30 12:02 UTC, merged