Change ContentType.objects.get to .get_for_model
acdh-oeaw/apis-core-rdf pull request #216
Opened 2023-06-21 08:38 UTC by richardhadden

**Describe your changes**

- Changed `ContentType.objects.get(model=<MODEL NAME>)` to `ContentType.objects.get_for_model(<MODEL>)`

**Additional context**
Due to case sensitivity issues in Postgres, looking up ContentTypes with the string name causes problems. Previously using the workaround script (https://github.com/acdh-oeaw/apis-ontologies/blob/8a561a50fee5220e0e93255c40cb152695531864/jelinek/ontology_specific_scripts/postgres_specific.py), but this causes further errors.

Instead, change the ContentType lookups to use the actual model, rather than the string name. There still seems to be some use of `ContentType.objects.get()` elsewhere; will investigate.

**Checklist (Replace the space in square brackets with a lowercase x for all that apply)**
- [X] My changes don't generate new warnings or errors
- [X] My changes follow the project's code formatting rules and style guidelines
- [ ] I have commented my code with Docstrings and code comments, particularly complex, unusual or hard-to-read code
- [ ] I have updated the project documentation to reflect the changes I introduce
- [ ] I have added new unit tests or updated existing ones to demonstrate my changes works

2023-06-21 08:43 UTC, richardhadden commented
Should check that this doesn't break anything with MariaDB instances (though I can't see why it would cause a problem)

2023-06-21 08:44 UTC, b1rger requested changes
Please change your commit message title to adhere to the [conventionalcommits](https://www.conventionalcommits.org) standard.
Please put the description of the change (what you wrote in the pull request) into the commit message - if we ever leave github, we lose the information, but if it is part of the commit history, we keep it.
You can change the last commit in a branch using `git commit --amend`. You can push the updated commit using `git push -f`

2023-06-21 08:51 UTC, richardhadden commented
@b1rger Sorry! Will read the rules more thoroughly!

2023-06-21 09:45 UTC, sennierer commented on apis_core/apis_relations/models.py
>              ):
test

2023-06-23 11:25 UTC, richardhadden commented
Is this ok to merge now? I can't use Postgres without this fix

2023-07-07 06:12 UTC, merged